import { Injectable } from '@nestjs/common'
import { DataSource, In } from 'typeorm'
import type { ChatGroupRuntimeView } from '@xpert-ai/contracts'
import { GroupAccessService } from './group-access.service'
import { GroupMessageRecipient, GroupParticipant } from './group.entity'
import { ChatConversation } from '../chat-conversation/conversation.entity'
import { ChatMessage } from '../chat-message/chat-message.entity'
import { XpertAgentExecution } from '../xpert-agent-execution/agent-execution.entity'
import { XpertWorkspaceAccessService } from '../xpert-workspace/workspace-access.service'
import { XpertProjectAccessService } from '../xpert-project/services/project-access.service'
import { parseGroupCommunication } from './group.schema'
import { groupDenied, groupConflict } from './group.errors'

/**
 * Invariants: group membership does not grant access to private execution records.
 * Recheck Assistant/workspace/project access and bind public message, runtime and execution within one scope.
 * Render in the existing external Assistant view; generated group context is replaced by public questions.
 */
@Injectable()
export class GroupRuntimeViewService {
    constructor(
        private readonly db: DataSource,
        private readonly access: GroupAccessService,
        private readonly workspaceAccess: XpertWorkspaceAccessService,
        private readonly projectAccess: XpertProjectAccessService
    ) {}

    /** Resolve a server-created publication or receipt link to one authorized execution and its message anchor. */
    async get(groupId: string, messageId: string, participantId: string): Promise<ChatGroupRuntimeView> {
        const { group } = await this.access.authorize(groupId)
        const scope = { tenantId: group.tenantId, organizationId: group.organizationId }
        const member = await this.db
            .getRepository(GroupParticipant)
            .findOneBy({ ...scope, id: participantId, groupId, kind: 'assistant', active: true })
        if (!member) throw groupDenied()
        const assistant = await this.access.assistant(member.subjectId)
        await this.workspaceAccess.assertCanRead(assistant.workspaceId)
        const runtime = await this.db.getRepository(ChatConversation).findOneBy({
            ...scope,
            id: member.runtimeConversationId,
            threadId: member.runtimeThreadId,
            purpose: 'group_assistant_runtime'
        })
        if (!runtime || runtime.xpertId !== member.subjectId) throw groupDenied()
        if (runtime.projectId) await this.projectAccess.assertCanReadXpert(runtime.projectId, member.subjectId)
        const source = await this.db
            .getRepository(ChatMessage)
            .findOneBy({ ...scope, id: messageId, conversationId: groupId })
        if (!source) throw groupDenied()
        let executionId: string | undefined
        let anchorId: string | undefined
        // These idempotency keys are generated by the server from persisted output/tool IDs, never from text.
        if (parseGroupCommunication(source.groupCommunication).senderId === participantId) {
            const outputId = source.groupPublicationId?.match(/^output:([0-9a-f-]{36})$/i)?.[1]
            if (outputId) {
                const output = await this.db
                    .getRepository(ChatMessage)
                    .findOneBy({ ...scope, id: outputId, conversationId: runtime.id, role: 'ai' })
                executionId = output?.executionId
                anchorId = output?.id
            } else {
                executionId = source.groupPublicationId?.match(/^tool:([0-9a-f-]{36}):/i)?.[1]
            }
        } else {
            const delivery = await this.db
                .getRepository(GroupMessageRecipient)
                .findOneBy({ ...scope, groupId, messageId, participantId })
            executionId = delivery?.executionId
            anchorId = delivery?.inputMessageId
        }
        if (!executionId) throw groupConflict()
        const execution = await this.db
            .getRepository(XpertAgentExecution)
            .findOneBy({ ...scope, id: executionId, threadId: runtime.threadId, xpertId: member.subjectId })
        if (!execution) throw groupDenied()
        const receipts = await this.db
            .getRepository(GroupMessageRecipient)
            .findBy({ ...scope, groupId, participantId, executionId })
        const inputIds = receipts.flatMap((receipt) => (receipt.inputMessageId ? [receipt.inputMessageId] : []))
        const rows = await this.db.getRepository(ChatMessage).find({
            where: [
                { ...scope, conversationId: runtime.id, executionId, role: In(['ai', 'human']) },
                ...(inputIds.length
                    ? [{ ...scope, conversationId: runtime.id, id: In(inputIds), role: 'human' as const }]
                    : [])
            ],
            order: { createdAt: 'ASC', id: 'ASC' }
        })
        const publicInputs = receipts.length
            ? await this.db
                  .getRepository(ChatMessage)
                  .findBy({ ...scope, conversationId: groupId, id: In(receipts.map((receipt) => receipt.messageId)) })
            : []
        return {
            conversationId: runtime.id,
            threadId: runtime.threadId,
            xpertId: member.subjectId,
            participantId,
            title: member.name,
            avatar: assistant.avatar,
            executionId,
            messageId: anchorId,
            status: execution.status,
            messages: rows.flatMap((row) => {
                // Replace the machine-generated group context with the actual public question.
                const input =
                    row.role === 'human'
                        ? publicInputs.find((input) =>
                              receipts.some(
                                  (receipt) => receipt.messageId === input.id && receipt.inputMessageId === row.id
                              )
                          )
                        : undefined
                if (row.role === 'human' && !input) return []
                return [
                    {
                        id: row.id,
                        role: row.role,
                        content: input?.content ?? row.content,
                        reasoning: row.reasoning,
                        status: row.status,
                        executionId: row.executionId,
                        createdAt: row.createdAt.toISOString()
                    }
                ]
            })
        }
    }
}
