packages:
  - 'apps/*'
  - 'libs/*'
  - 'packages/*'
  - 'packages/plugins/*'
  - 'docs'
  - 'legacies/*'

overrides:
  '@xpert-ai/plugin-sdk': workspace:*
  '@langchain/core': 0.3.72
  langchain: 0.3.31
  '@modelcontextprotocol/sdk': 1.12.1
  '@modelcontextprotocol/ext-apps>@modelcontextprotocol/sdk': 1.29.0
  '@xpert-ai/plugin-echarts-mcp-app>@modelcontextprotocol/sdk': 1.29.0
  zod: 3.25.67
  web-streams-polyfill: ^4.2.0

allowBuilds:
  '@apollo/protobufjs': true
  '@compodoc/compodoc': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  aws-sdk: true
  core-js: true
  cypress: true
  es5-ext: true
  esbuild: true
  ffmpeg-ffprobe-static: true
  isolated-vm: true
  less: true
  lmdb: true
  msgpackr-extract: true
  ngx-float-ui: true
  ngx-popperjs: true
  node-pty: true
  nx: true
  protobufjs: true
  sharp: true
  swiper: true
  unrs-resolver: true
