const { translate } = require('./i18n/index.mjs')
const { ClientError } = require('./service.cjs')
const methods = new Set([
  'bosiSetup',
  'bosiWorkspace',
  'createBosi',
  'bosiWelcome',
  'bosiConnections',
  'bosiOnboarding',
  'bosiChoose',
  'bosiConnect',
  'bosiCheckConnection',
  'assistantAppearance',
  'saveAssistantAppearance',
  'uploadAssistantAvatar',
  'assistantPetAsset',
  'assistantPetCatalog',
  'uploadAssistantPet',
  'voiceCapability',
  'voiceStart',
  'voiceEnd',
  'usageMembership',
  'usagePeriods',
  'usageOverview',
  'usageSummaries',
  'usageEntries',
  'state',
  'refreshProfile',
  'shellState',
  'shellPrepare',
  'shellConfigure',
  'shellDecide',
  'shellPolicy',
  'shellEnable',
  'shellDisable',
  'shellBind',
  'shellUnbind',
  'shellOperations',
  'shellCancel',
  'configure',
  'checkConnectionCertificates',
  'login',
  'loginLocal',
  'selectOrganization',
  'listBots',
  'sidebarState',
  'updateSidebar',
  'botActivity',
  'botConversation',
  'botProfile',
  'assistantTriggers',
  'saveAssistantTrigger',
  'validateAssistantTrigger',
  'assistantTriggerOptions',
  'assistantTriggerManageUrl',
  'beginAssistantTriggerQr',
  'pollAssistantTriggerQr',
  'completeAssistantTriggerQr',
  'cancelAssistantTriggerQr',
  'botConversations',
  'botProfileViews',
  'openProfileView',
  'closeProfileView',
  'profileViewRequest',
  'markBotRead',
  'markAllBotRead',
  'editBot',
  'assistantConfiguration',
  'saveAssistantConfiguration',
  'duplicateBot',
  'chatSession',
  'toolOutputPreview',
  'deliveredFilePreview',
  'workbenchSession',
  'listCatalog',
  'pluginConnection',
  'startPluginConnection',
  'checkPluginConnection',
  'cancelPluginConnection',
  'pluginLibrary',
  'addWorkspacePlugin',
  'requestExpertAccess',
  'applicationSetup',
  'initializeApplication',
  'templateWorkspaces',
  'templateSetup',
  'installTemplate',
  'logout'
])
async function dispatch(service, method, argument) {
  try {
    if (!methods.has(method)) throw new ClientError('Unsupported operation.', 403)
    return { ok: true, value: await service[method](argument) }
  } catch (error) {
    return {
      ok: false,
      message: translate(
        service.config.locale,
        error instanceof ClientError ? error.key : 'The operation failed. Please retry.',
        error instanceof ClientError ? error.params : {}
      ),
      key: error instanceof ClientError ? error.key : 'The operation failed. Please retry.',
      params: error instanceof ClientError ? error.params : {},
      status: error.status || 500
    }
  }
}
module.exports = { dispatch }
