import { ConflictException } from '@nestjs/common'
import { IKnowledgeDocument } from '@xpert-ai/contracts'
import { t } from 'i18next'

/** User mutation entry points must not overwrite a generated publication's source of truth. */
export function assertUserManagedDocument(document: Pick<IKnowledgeDocument, 'metadata'>): void {
    if (document.metadata?.systemManaged === true) {
        const defaultValue =
            'This document is generated by the system. Update and republish it from its source application.'
        throw new ConflictException(
            t('server-ai:Error.KnowledgeDocumentManagedReadOnly', { defaultValue }) || defaultValue
        )
    }
}
