import { AnalyticsFeatures, IFeatureCreateInput } from '@xpert-ai/contracts'


export const DEFAULT_FEATURES: Partial<IFeatureCreateInput>[] = [
	{
		name: 'Business Area',
		code: AnalyticsFeatures.FEATURE_BUSINESS_AREA,
		description: 'Manage Business Areas',
		image: 'estimate.png',
		link: 'business-area',
		isEnabled: true,
		icon: 'file-text-outline',
		status: 'success',
	},
	{
		name: 'Data Source',
		code: AnalyticsFeatures.FEATURE_DATA_SOURCE,
		description: 'Manage Data Sources',
		image: 'estimate.png',
		link: 'settings/data-sources',
		isEnabled: true,
		icon: 'database',
		status: 'success',
	},
	{
		name: 'Semantic Model',
		code: AnalyticsFeatures.FEATURE_MODEL,
		description: 'Manage and View Semantic Model',
		image: 'estimate.png',
		link: 'model',
		isEnabled: true,
		icon: 'file-text-outline',
		status: 'success',
	},
	{
		name: 'Story',
		code: AnalyticsFeatures.FEATURE_STORY,
		description: 'Manage and View Story',
		image: 'estimate.png',
		link: 'story',
		isEnabled: true,
		icon: 'file-text-outline',
		status: 'success',
	},
	{
		name: 'Project',
		code: AnalyticsFeatures.FEATURE_PROJECT,
		description: 'Go to Project, Manage Story and Indicator',
		image: 'project.png',
		link: 'project',
		isEnabled: true,
		icon: 'project-outline',
		status: 'success',
	},
	// {
	// 	name: 'Data Factory',
	// 	code: AnalyticsFeatures.FEATURE_DATA_FACTORY,
	// 	description: 'Go to data factory to manage data',
	// 	image: 'data-factory.png',
	// 	link: 'data',
	// 	isEnabled: true,
	// 	icon: 'data-factory',
	// 	status: 'success',
	// }
]
