export const AI_BOOTSTRAP_QUEUE = 'server-ai-bootstrap'
export const AI_ORGANIZATION_BOOTSTRAP_JOB = 'organization-bootstrap'
export const AI_TENANT_SKILL_REPOSITORY_BOOTSTRAP_JOB = 'tenant-skill-repository-bootstrap'
export const AI_USER_ORGANIZATION_BOOTSTRAP_JOB = 'user-organization-bootstrap'
export const AI_USER_DEFAULT_WORKSPACE_SKILLS_BOOTSTRAP_JOB = 'user-default-workspace-skills-bootstrap'
export const AI_USER_ORGANIZATION_CLEANUP_JOB = 'user-organization-cleanup'
export const AI_ORGANIZATION_SKILL_REPOSITORY_SYNC_JOB = 'organization-skill-repository-sync'

export const DEFAULT_ORGANIZATION_WORKSPACE_NAME = 'Default Workspace'
export const DEFAULT_ENVIRONMENT_NAME = 'Default'
