export const CLASS_NAME_COL6 = 'xp-formly__col xp-formly__col-6'
export const CLASS_NAME_COL12 = 'xp-formly__col xp-formly__col-12'
export const FORMLY_W_FULL = 'xp-formly__col xp-formly__col-12'
export const FORMLY_W_1_3 = 'xp-formly__col xp-formly__col-4'
export const FORMLY_W_2_3 = 'xp-formly__col xp-formly__col-8'
export const FORMLY_W_1_2 = 'xp-formly__col xp-formly__col-6'
export const FORMLY_W_NONE = 'xp-formly__col_none'
export const FORMLY_ROW = 'xp-formly__row'
