import { Observable } from 'rxjs'
import { PeriodFunctions } from './annotations'
import { DataSource } from './data-source'
import { CalculatedProperty, EntityType, IDimensionMember, Indicator, Property, QueryReturn } from './models'
import { Annotation, AnnotationTerm, Dimension, QueryOptions } from './types'

/**
 * CURD service for entity
 */
export interface EntityService<T> {
  __id__?: string
  dataSource: DataSource
  entitySet: string

  /**
   * Get EntityType
   */
  selectEntityType(): Observable<EntityType>

  /**
   * @deprecated use `selectQuery`
   * Query
   * @param options 
   */
  query(options?: QueryOptions): Observable<QueryReturn<T>>

  selectQuery(options?: QueryOptions): Observable<QueryReturn<T>>

  /**
   * Refresh
   */
  refresh(): void

  /**
   * Get the specified annotation of the current entity
   *
   * @param term Type of annotation
   * @param qualifier Annotation identifier, optional
   */
  getAnnotation<AT extends Annotation>(term: AnnotationTerm, qualifier?: string): Observable<AT>

  /**
   * @deprecated use selectMembers
   * 
   * Get all members of a field dimension
   */
  getMembers(property: Dimension): Observable<Array<IDimensionMember>>
  selectMembers(property: Dimension): Observable<Array<IDimensionMember>>

  /**
   * Register a provisional indicator definition to measure
   * 
   * @param name Measure name
   * @param property Indicator definition
   */
  registerMeasure(name: string, property: CalculatedProperty): void

  /**
   * Get calculated measure member generated by common functions
   *
   * @param measure The name of indicator-based measure
   * @param type Time period function for indicator
   * @param calendar Calendar hierarchy name
   */
  getCalculatedMember(measure: string, type: PeriodFunctions, calendar?: string): Property

  /**
   * @deprecated use getIndicator in DataSource ?
   * 
   * @param id 
   */
  getIndicator(idOrCode: string): Indicator

  selectIndicator(idOrCode: string): Observable<Indicator>

  /**
   * Completes all relevant Observable streams.
   */
  onDestroy(): void
}
