import {
    ChecklistItem,
    convertToUrlPath,
    IXpertMemoryRecord,
    MemoryAudienceEnum,
    IUser,
    LongTermMemoryTypeEnum,
    TMemoryAudience,
    TMemoryFileEntry,
    TMemoryGovernanceAction,
    TMemoryQA,
    TMemoryUserProfile,
    TXpertMemoryFiles,
    TXpertTeamDraft
} from '@metad/contracts'
import { getErrorMessage } from '@metad/server-common'
import {
    OptionParams,
    PaginationParams,
    RequestContext,
    TenantOrganizationAwareCrudService,
    transformWhere,
    UserPublicDTO,
    UserService
} from '@metad/server-core'
import { HttpException, HttpStatus, Injectable, NotFoundException } from '@nestjs/common'
import { CommandBus, QueryBus } from '@nestjs/cqrs'
import { EventEmitter2 } from '@nestjs/event-emitter'
import { InjectRepository } from '@nestjs/typeorm'
import { WorkflowTriggerRegistry } from '@xpert-ai/plugin-sdk'
import { assign, uniq, uniqBy } from 'lodash'
import { FindOptionsWhere, In, IsNull, Not, Repository } from 'typeorm'
import { SandboxService } from '../sandbox/sandbox.service'
import { DEFAULT_MEMORY_PROVIDER_NAME, MemoryRegistry } from '../xpert-memory'
import { GetXpertWorkspaceQuery, MyXpertWorkspaceQuery } from '../xpert-workspace'
import { XpertPublishCommand } from './commands'
import { XpertIdentiDto } from './dto'
import { EventNameXpertValidate, XpertDraftValidateEvent } from './types'
import { FreeNodeValidator } from './validators'
import { Xpert } from './xpert.entity'

@Injectable()
export class XpertService extends TenantOrganizationAwareCrudService<Xpert> {
    constructor(
        @InjectRepository(Xpert)
        public readonly repository: Repository<Xpert>,
        private readonly userService: UserService,
        private readonly commandBus: CommandBus,
        private readonly queryBus: QueryBus,
        private readonly eventEmitter: EventEmitter2,
        private readonly triggerRegistry: WorkflowTriggerRegistry,
        private readonly sandboxService: SandboxService,
        private readonly memoryRegistry: MemoryRegistry
    ) {
        super(repository)
    }

    private get memoryProvider() {
        return this.memoryRegistry.getProviderOrThrow(DEFAULT_MEMORY_PROVIDER_NAME)
    }

    /**
     * To solve the problem that Update cannot create OneToOne relation, it is uncertain whether using save to update might pose risks
     */
    async update(id: string, entity: Partial<Xpert>) {
        const _entity = await super.findOne(id)
        assign(_entity, entity)
        return await this.repository.save(_entity)
    }

    /**
     * Verify the uniqueness of the slug generated by Name in the system to ensure that it is unique across the entire database
     *
     * @param name
     * @returns
     */
    async validateName(name: string) {
        const slug = convertToUrlPath(name)
        if (slug.length < 5) {
            return false
        }
        const count = await this.repository.count({
            where: {
                slug,
                latest: true
            }
        })

        return !count
    }

    async getAllByWorkspace(workspaceId: string, data: PaginationParams<Xpert>, published: boolean, user: IUser) {
        const { select, relations, order, take } = data ?? {}
        let { where } = data ?? {}
        where = transformWhere(where ?? {})
        if (workspaceId === 'null' || workspaceId === 'undefined' || !workspaceId) {
            where = {
                ...(<FindOptionsWhere<Xpert>>where),
                workspaceId: IsNull(),
                createdById: user.id
            }
        } else {
            const workspace = await this.queryBus.execute(new GetXpertWorkspaceQuery(user, { id: workspaceId }))
            if (!workspace) {
                throw new NotFoundException(`Not found or no auth for xpert workspace '${workspaceId}'`)
            }

            where = {
                ...(<FindOptionsWhere<Xpert>>where),
                workspaceId: workspaceId
            }
        }
        if (published) {
            where.version = Not(IsNull())
        }

        return this.findAll({
            select,
            where,
            relations,
            order,
            take
        })
    }

    async countMy(where: FindOptionsWhere<Xpert>) {
        const userId = RequestContext.currentUserId()
        const { items: userWorkspaces } = await this.queryBus.execute(new MyXpertWorkspaceQuery(userId, {}))

        where = {
            ...(<FindOptionsWhere<Xpert>>where ?? {}),
            publishAt: Not(IsNull()),
            createdById: userId
        }

        const xpertsCreatedByUser = await this.findAll({
            select: ['id'],
            where
        })

        const baseQuery = this.repository
            .createQueryBuilder('xpert')
            .innerJoin('xpert.managers', 'manager', 'manager.id = :userId', { userId })

        const xpertsManagedByUser = await baseQuery
            .where({
                ...(where ?? {}),
                publishAt: Not(IsNull()),
                tenantId: RequestContext.currentTenantId(),
                organizationId: RequestContext.getOrganizationId()
            })
            .select(['xpert.id'])
            .getMany()

        const xpertsInUserWorkspaces = await this.repository.find({
            where: {
                ...(where ?? {}),
                publishAt: Not(IsNull()),
                workspaceId: In(userWorkspaces.map((workspace) => workspace.id))
            },
            select: ['id']
        })

        const allXperts = uniqBy(
            [...xpertsCreatedByUser.items, ...xpertsManagedByUser, ...xpertsInUserWorkspaces],
            'id'
        )

        return allXperts.length
    }

    async getMyAll(params: PaginationParams<Xpert>) {
        const userId = RequestContext.currentUserId()
        const { items: userWorkspaces } = await this.queryBus.execute(new MyXpertWorkspaceQuery(userId, {}))

        const { relations, order, take } = params ?? {}
        let { where } = params ?? {}
        where = where ?? {}

        where = {
            ...(<FindOptionsWhere<Xpert>>where),
            publishAt: Not(IsNull()),
            createdById: userId
        }

        const xpertsCreatedByUser = await this.findAll({
            where,
            relations,
            order,
            take
        })

        const baseQuery = this.repository
            .createQueryBuilder('xpert')
            .innerJoin('xpert.managers', 'manager', 'manager.id = :userId', { userId })
        // add relations
        relations?.forEach((relation) => baseQuery.leftJoinAndSelect('xpert.' + relation, relation))
        if (order) {
            Object.keys(order).forEach((name) => {
                baseQuery.addOrderBy(`xpert.${name}`, order[name])
            })
        }
        const xpertsManagedByUser = await baseQuery
            .where({
                ...(params.where ?? {}),
                publishAt: Not(IsNull()),
                tenantId: RequestContext.currentTenantId(),
                organizationId: RequestContext.getOrganizationId()
            })
            .take(take)
            .getMany()

        const xpertsInUserWorkspaces = await this.repository.find({
            where: {
                ...(params.where ?? {}),
                publishAt: Not(IsNull()),
                workspaceId: In(userWorkspaces.map((workspace) => workspace.id))
            },
            relations,
            order,
            take
        })

        const allXperts = uniqBy(
            [...xpertsCreatedByUser.items, ...xpertsManagedByUser, ...xpertsInUserWorkspaces],
            'id'
        )

        return {
            items: allXperts.map((item) => new XpertIdentiDto(item)),
            total: allXperts.length
        }
    }

    async getTeam(id: string, options?: OptionParams<Xpert>) {
        const { relations } = options ?? {}
        const team = await this.findOne(id, {
            relations: uniq([...(relations ?? []), 'agents', 'toolsets', 'knowledgebases'])
        })
        return team
    }

    async save(entity: Xpert) {
        return await this.repository.save(entity)
    }

    async saveDraft(id: string, draft: TXpertTeamDraft) {
        const xpert = await this.findOne(id)
        xpert.draft = {
            ...draft,
            team: {
                ...draft.team,
                updatedAt: new Date(),
                updatedById: RequestContext.currentUserId()
            }
        } as TXpertTeamDraft

        xpert.draft.checklist = await this.validate(xpert.draft)

        await this.repository.save(xpert)
        return xpert.draft
    }

    async updateDraft(id: string, draft: TXpertTeamDraft) {
        const xpert = await this.findOne(id)
        xpert.draft = {
            ...(xpert.draft ?? {}),
            ...draft,
            team: {
                ...(xpert.draft?.team ?? {}),
                ...(draft.team ?? {}),
                updatedAt: new Date(),
                updatedById: RequestContext.currentUserId()
            }
        } as TXpertTeamDraft

        xpert.draft.checklist = await this.validate(xpert.draft)

        await this.repository.save(xpert)
        return xpert.draft
    }

    async validate(draft: TXpertTeamDraft) {
        const freeNodeValidator = new FreeNodeValidator()

        const results: ChecklistItem[] = []

        const res = await freeNodeValidator.validate(draft)
        results.push(...res)

        // More validators events
        const validators = await this.eventEmitter.emitAsync(EventNameXpertValidate, new XpertDraftValidateEvent(draft))
        validators.forEach((items) => {
            if (items) {
                results.push(...items)
            }
        })
        return results
    }

    async publish(id: string, newVersion: boolean, environmentId: string, notes: string) {
        return await this.commandBus.execute(new XpertPublishCommand(id, newVersion, environmentId, notes))
    }

    async allVersions(id: string) {
        const xpert = await this.findOne(id)
        const { items: allVersions } = await this.findAll({
            where: {
                workspaceId: xpert.workspaceId ?? IsNull(),
                type: xpert.type,
                slug: xpert.slug
            }
        })

        return allVersions.map((item) => ({
            id: item.id,
            version: item.version,
            latest: item.latest,
            publishAt: item.publishAt,
            releaseNotes: item.releaseNotes
        }))
    }

    async setAsLatest(id: string) {
        const xpert = await this.findOne(id)
        if (!xpert.latest) {
            const { items: xperts } = await this.findAll({
                where: {
                    workspaceId: xpert.workspaceId ?? IsNull(),
                    type: xpert.type,
                    slug: xpert.slug,
                    latest: true
                }
            })

            xperts.forEach((item) => (item.latest = false))
            xpert.latest = true
            await this.repository.save([...xperts, xpert])
        }
    }

    async deleteXpert(id: string) {
        const xpert = await this.findOne(id)

        if (xpert.latest) {
            // Delete all versions if it is latest version
            return await this.softDelete({ name: xpert.name, deletedAt: IsNull() })
        } else {
            // Delete current version team
            return await this.softDelete(xpert.id)
        }
    }

    async updateManagers(id: string, ids: string[]) {
        const xpert = await this.findOne(id, { relations: ['managers'] })
        const { items } = await this.userService.findAll({ where: { id: In(ids) } })
        xpert.managers = items
        await this.repository.save(xpert)
        return xpert.managers.map((u) => new UserPublicDTO(u))
    }

    async removeManager(id: string, userId: string) {
        const xpert = await this.findOne(id, { relations: ['managers'] })
        if (!xpert) {
            throw new NotFoundException(`Xpert with id ${id} not found`)
        }

        const managerIndex = xpert.managers.findIndex((manager) => manager.id === userId)
        if (managerIndex === -1) {
            throw new NotFoundException(`Manager with id ${userId} not found in Xpert ${id}`)
        }

        xpert.managers.splice(managerIndex, 1)
        await this.repository.save(xpert)
    }

    async findBySlug(slug: string, relations?: string[]) {
        return await this.repository.findOne({
            where: {
                slug,
                latest: true,
                publishAt: Not(IsNull())
            },
            relations: uniq((relations ?? []).concat(['user', 'createdBy', 'organization']))
        })
    }

    async createMemory(
        xpertId: string,
        body: {
            type: LongTermMemoryTypeEnum
            value: TMemoryQA | TMemoryUserProfile
            audience?: TMemoryAudience
            source?: string
            sourceRef?: string
            tags?: string[]
        }
    ) {
        const xpert = await this.findOne(xpertId)
        const record = await this.memoryProvider.upsert(xpert.tenantId, {
            scope: this.memoryProvider.resolveScope(xpert),
            audience: body.audience,
            kind: body.type,
            value: body.value,
            tags: body.tags,
            source: body.source ?? 'manual',
            sourceRef: body.sourceRef,
            createdBy: RequestContext.currentUserId()
        })

        return (await this.attachMemoryUsers([this.memoryProvider.toApiRecord(record)]))[0]
    }

    async updateMemory(
        xpertId: string,
        memoryId: string,
        body: {
            type?: LongTermMemoryTypeEnum
            audience?: TMemoryAudience
            ownerUserId?: string
            value?: TMemoryQA | TMemoryUserProfile
            title?: string
            content?: string
            context?: string
            tags?: string[]
            action?: TMemoryGovernanceAction
        }
    ) {
        const xpert = await this.findOne(xpertId)
        const scope = this.memoryProvider.resolveScope(xpert)
        const userId = RequestContext.currentUserId()

        let record = null
        if (body.action) {
            record = await this.memoryProvider.applyGovernance(xpert.tenantId, scope, memoryId, body.action, userId, {
                userId,
                audience: body.audience ?? 'all',
                ownerUserId: body.ownerUserId
            })
        } else {
            const existing = await this.memoryProvider.get(xpert.tenantId, scope, memoryId, {
                userId,
                audience: body.audience ?? 'all',
                ownerUserId: body.ownerUserId
            })
            if (!existing) {
                throw new NotFoundException(`Memory with id ${memoryId} not found`)
            }

            record = await this.memoryProvider.upsert(xpert.tenantId, {
                scope,
                audience: body.audience ?? existing.audience,
                ownerUserId: body.ownerUserId ?? existing.ownerUserId,
                kind: body.type ?? existing.kind,
                memoryId,
                title: body.title,
                content: body.content,
                context: body.context,
                value: body.value,
                tags: body.tags ?? existing.tags,
                source: String(existing.source ?? 'manual'),
                sourceRef: existing.sourceRef,
                createdBy: String(existing.createdBy),
                updatedBy: userId,
                status: existing.status
            })
        }

        return record ? (await this.attachMemoryUsers([this.memoryProvider.toApiRecord(record)]))[0] : null
    }

    async createBulkMemories(
        xpertId: string,
        body: {
            type: LongTermMemoryTypeEnum
            memories: Array<TMemoryQA | TMemoryUserProfile>
            audience?: TMemoryAudience
            source?: string
            sourceRef?: string
        }
    ) {
        const xpert = await this.findOne(xpertId)
        const scope = this.memoryProvider.resolveScope(xpert)
        const records = await this.memoryProvider.bulkUpsert(
            xpert.tenantId,
            body.memories.map((value) => ({
                scope,
                audience: body.audience,
                kind: body.type,
                value,
                source: body.source ?? 'manual',
                sourceRef: body.sourceRef,
                createdBy: RequestContext.currentUserId()
            }))
        )

        return this.attachMemoryUsers(records.map((record) => this.memoryProvider.toApiRecord(record)))
    }

    async findAllMemory(
        id: string,
        types: string[],
        options?: {
            includeArchived?: boolean
            includeFrozen?: boolean
            audience?: TMemoryAudience | 'all'
        }
    ) {
        try {
            const xpert = await this.findOne(id)
            const items = await this.memoryProvider.list(xpert.tenantId, this.memoryProvider.resolveScope(xpert), {
                kinds: normalizeMemoryKinds(types),
                includeArchived: options?.includeArchived,
                includeFrozen: options?.includeFrozen,
                audience: options?.audience ?? 'all',
                userId: RequestContext.currentUserId()
            })
            const records = await this.attachMemoryUsers(items.map((item) => this.memoryProvider.toApiRecord(item)))
            return {
                items: records,
                total: records.length
            }
        } catch (err) {
            throw new HttpException(getErrorMessage(err), HttpStatus.INTERNAL_SERVER_ERROR)
        }
    }

    async searchMemory(
        id: string,
        body: {
            type?: LongTermMemoryTypeEnum
            audience?: TMemoryAudience | 'all'
            text?: string
            includeArchived?: boolean
            includeFrozen?: boolean
            limit?: number
        }
    ) {
        const xpert = await this.findOne(id)
        const items = await this.memoryProvider.search(xpert.tenantId, this.memoryProvider.resolveScope(xpert), {
            kinds: body.type ? [body.type] : undefined,
            audience: body.audience ?? 'all',
            userId: RequestContext.currentUserId(),
            text: body.text,
            includeArchived: body.includeArchived,
            includeFrozen: body.includeFrozen,
            limit: body.limit
        })

        return this.attachMemoryUsers(items.map((item) => this.memoryProvider.toApiRecord(item)))
    }

    async archiveAllMemory(id: string) {
        const xpert = await this.findOne(id)
        const items = await this.memoryProvider.archiveAll(
            xpert.tenantId,
            this.memoryProvider.resolveScope(xpert),
            RequestContext.currentUserId(),
            {
                userId: RequestContext.currentUserId(),
                audience: 'all'
            }
        )
        return {
            items: await this.attachMemoryUsers(items.map((item) => this.memoryProvider.toApiRecord(item))),
            total: items.length
        }
    }

    async getMemoryFiles(id: string): Promise<TXpertMemoryFiles> {
        const xpert = await this.findOne(id)
        return this.memoryProvider.listFiles(
            xpert.tenantId,
            this.memoryProvider.resolveScope(xpert),
            RequestContext.currentUserId()
        )
    }

    async updateMemoryFile(
        id: string,
        body: {
            audience: TMemoryAudience
            ownerUserId?: string
            path: string
            content: string
        }
    ): Promise<TMemoryFileEntry> {
        const xpert = await this.findOne(id)
        return this.memoryProvider.updateFileContent(xpert.tenantId, {
            scope: this.memoryProvider.resolveScope(xpert),
            userId: RequestContext.currentUserId(),
            audience: body.audience ?? MemoryAudienceEnum.SHARED,
            ownerUserId: body.ownerUserId,
            path: body.path,
            content: body.content,
            updatedBy: RequestContext.currentUserId()
        })
    }

    private async attachMemoryUsers(items: IXpertMemoryRecord[]): Promise<IXpertMemoryRecord[]> {
        const userIds = Array.from(
            new Set(
                items
                    .flatMap((item) => [item.createdBy, item.updatedBy])
                    .filter((value): value is string => typeof value === 'string' && !!value)
            )
        )

        if (!userIds.length) {
            return items
        }

        const { items: users } = await this.userService.findAll({
            where: {
                id: In(userIds)
            }
        })
        const userMap = new Map(users.map((user) => [user.id, new UserPublicDTO(user)]))

        return items.map((item) => ({
            ...item,
            createdBy:
                typeof item.createdBy === 'string' ? (userMap.get(item.createdBy) ?? item.createdBy) : item.createdBy,
            updatedBy:
                typeof item.updatedBy === 'string' ? (userMap.get(item.updatedBy) ?? item.updatedBy) : item.updatedBy
        }))
    }

    async getTriggerProviders() {
        return this.triggerRegistry.list().map((provider) => ({
            ...provider.meta
        }))
    }

    async getSandboxProviders() {
        return this.sandboxService.listProviders()
    }
}

function normalizeMemoryKinds(types?: string[]) {
    const validKinds = new Set(Object.values(LongTermMemoryTypeEnum))
    return (types ?? []).filter((type): type is LongTermMemoryTypeEnum =>
        validKinds.has(type as LongTermMemoryTypeEnum)
    )
}
