import {
    ChecklistItem,
    convertToUrlPath,
    ICopilotStore,
    IUser,
    IXpertAgentExecution,
    LongTermMemoryTypeEnum,
    normalizeMiddlewareNodes,
    normalizeXpertAgentConfig,
    OrderTypeEnum,
    TFile,
    TFileDirectory,
    TMemoryQA,
    TMemoryUserProfile,
    TXpertTeamDraft
} from '@xpert-ai/contracts'
import { getErrorMessage } from '@xpert-ai/server-common'
import {
    OptionParams,
    PaginationParams,
    RequestContext,
    transformWhere,
    UserGroupService
} from '@xpert-ai/server-core'
import { HttpException, HttpStatus, Inject, Injectable, NotFoundException } from '@nestjs/common'
import { CommandBus, QueryBus } from '@nestjs/cqrs'
import { EventEmitter2 } from '@nestjs/event-emitter'
import { InjectRepository } from '@nestjs/typeorm'
import { WorkflowTriggerRegistry } from '@xpert-ai/plugin-sdk'
import { assign, uniq, uniqBy } from 'lodash'
import { DeepPartial, FindOptionsWhere, In, IsNull, Like, Not, Repository } from 'typeorm'
import { CopilotStoreBulkPutCommand } from '../copilot-store'
import { CopilotStoreService } from '../copilot-store/copilot-store.service'
import { SandboxService } from '../sandbox/sandbox.service'
import { VOLUME_CLIENT, VolumeClient, VolumeSubtreeClient } from '../shared/volume'
import { MyXpertWorkspaceQuery } from '../xpert-workspace/queries'
import { XpertWorkspaceAccessService } from '../xpert-workspace/workspace-access.service'
import { XpertWorkspaceBaseService } from '../xpert-workspace/workspace-base.service'
import { XpertPublishCommand } from './commands'
import { XpertIdentiDto } from './dto'
import { GetXpertMemoryEmbeddingsQuery } from './queries'
import { EventNameXpertValidate, XpertDraftValidateEvent } from './types'
import { FreeNodeValidator } from './validators'
import { Xpert } from './xpert.entity'

const XPERT_MEMORY_WORKSPACE_PATH = '.xpert/memory'

@Injectable()
export class XpertService extends XpertWorkspaceBaseService<Xpert> {
    constructor(
        @InjectRepository(Xpert)
        public readonly repository: Repository<Xpert>,
        workspaceAccessService: XpertWorkspaceAccessService,
        private readonly storeService: CopilotStoreService,
        private readonly userGroupService: UserGroupService,
        protected readonly commandBus: CommandBus,
        protected readonly queryBus: QueryBus,
        private readonly eventEmitter: EventEmitter2,
        private readonly triggerRegistry: WorkflowTriggerRegistry,
        private readonly sandboxService: SandboxService,
        @Inject(VOLUME_CLIENT)
        private readonly volumeClient: VolumeClient
    ) {
        super(repository, workspaceAccessService)
    }

    /**
     * To solve the problem that Update cannot create OneToOne relation, it is uncertain whether using save to update might pose risks
     */
    async update(id: string, entity: Partial<Xpert>) {
        const _entity = await super.findOne(id)
        assign(_entity, entity)
        return await super.save(_entity)
    }

    async create(entity: DeepPartial<Xpert>, ...options: unknown[]) {
        return await super.create(
            {
                ...entity,
                agentConfig: normalizeXpertAgentConfig(entity.agentConfig)
            },
            ...options
        )
    }

    /**
     * Verify the uniqueness of the slug generated by Name in the system to ensure that it is unique across the entire database
     *
     * @param name
     * @returns
     */
    async validateName(name: string) {
        const slug = convertToUrlPath(name)
        if (slug.length < 5) {
            return false
        }
        const count = await this.repository.count({
            where: {
                slug,
                latest: true
            }
        })

        return !count
    }

    async getAllByWorkspace(workspaceId: string, data: PaginationParams<Xpert>, published: boolean, user: IUser) {
        const { select, relations, order, take } = data ?? {}
        let { where } = data ?? {}
        where = transformWhere(where ?? {})
        if (workspaceId === 'null' || workspaceId === 'undefined' || !workspaceId) {
            where = {
                ...(<FindOptionsWhere<Xpert>>where),
                workspaceId: IsNull(),
                createdById: user.id
            }
        } else {
            await this.assertWorkspaceReadAccess(workspaceId)
            where = {
                ...(<FindOptionsWhere<Xpert>>where),
                workspaceId: workspaceId
            }
        }
        if (published) {
            where.version = Not(IsNull())
        }

        return this.findAll({
            select,
            where,
            relations,
            order,
            take
        })
    }

    async countMy(where: FindOptionsWhere<Xpert>) {
        const userId = RequestContext.currentUserId()
        const { items: userWorkspaces } = await this.queryBus.execute(new MyXpertWorkspaceQuery(userId, {}))

        where = {
            ...(<FindOptionsWhere<Xpert>>where ?? {}),
            publishAt: Not(IsNull()),
            createdById: userId
        }

        const xpertsCreatedByUser = await this.findAll({
            select: ['id'],
            where
        })

        const xpertsInUserWorkspaces = await this.repository.find({
            where: {
                ...(where ?? {}),
                publishAt: Not(IsNull()),
                workspaceId: In(userWorkspaces.map((workspace) => workspace.id))
            },
            select: ['id']
        })

        const allXperts = uniqBy([...xpertsCreatedByUser.items, ...xpertsInUserWorkspaces], 'id')

        return allXperts.length
    }

    async getMyAll(params: PaginationParams<Xpert>) {
        const userId = RequestContext.currentUserId()
        const { items: userWorkspaces } = await this.queryBus.execute(new MyXpertWorkspaceQuery(userId, {}))

        const { relations, order, take } = params ?? {}
        let { where } = params ?? {}
        where = where ?? {}

        where = {
            ...(<FindOptionsWhere<Xpert>>where),
            publishAt: Not(IsNull()),
            createdById: userId
        }

        const xpertsCreatedByUser = await this.findAll({
            where,
            relations,
            order,
            take
        })

        const xpertsInUserWorkspaces = await this.repository.find({
            where: {
                ...(params.where ?? {}),
                publishAt: Not(IsNull()),
                workspaceId: In(userWorkspaces.map((workspace) => workspace.id))
            },
            relations,
            order,
            take
        })

        const allXperts = uniqBy([...xpertsCreatedByUser.items, ...xpertsInUserWorkspaces], 'id')

        return {
            items: allXperts.map((item) => new XpertIdentiDto(item)),
            total: allXperts.length
        }
    }

    async getTeam(id: string, options?: OptionParams<Xpert>) {
        const { relations } = options ?? {}
        const team = await this.findOne(id, {
            relations: uniq([...(relations ?? []), 'agents', 'toolsets', 'knowledgebases'])
        })
        return team
    }

    async findOneByIdWithinTenant(
        id: string,
        options?: Partial<Pick<OptionParams<Xpert>, 'relations' | 'select' | 'withDeleted'>>
    ) {
        const tenantId = RequestContext.currentTenantId()

        const entity = await this.repository.findOne({
            ...(options ?? {}),
            where: {
                id,
                tenantId
            }
        })

        if (!entity) {
            throw new NotFoundException(`Not found xpert '${id}' in current tenant`)
        }

        return entity
    }

    async save(entity: Xpert) {
        return await super.save({
            ...entity,
            agentConfig: normalizeXpertAgentConfig(entity.agentConfig)
        })
    }

    async saveDraft(id: string, draft: TXpertTeamDraft) {
        const xpert = await this.findOne(id)
        xpert.draft = {
            ...draft,
            nodes: normalizeMiddlewareNodes(draft.nodes),
            team: {
                ...draft.team,
                updatedAt: new Date(),
                updatedById: RequestContext.currentUserId()
            }
        } as TXpertTeamDraft

        xpert.draft.checklist = await this.validate(xpert.draft)

        await super.save(xpert)
        return xpert.draft
    }

    async updateDraft(id: string, draft: Partial<TXpertTeamDraft>) {
        const xpert = await this.findOne(id)
        xpert.draft = {
            ...(xpert.draft ?? {}),
            ...draft,
            nodes: normalizeMiddlewareNodes(draft.nodes ?? xpert.draft?.nodes ?? xpert.graph?.nodes),
            connections: draft.connections ?? xpert.draft?.connections ?? xpert.graph?.connections,
            team: {
                ...(xpert.draft?.team ?? {}),
                ...(draft.team ?? {}),
                updatedAt: new Date(),
                updatedById: RequestContext.currentUserId()
            }
        } as TXpertTeamDraft

        xpert.draft.checklist = await this.validate(xpert.draft)

        await this.repository.save(xpert)
        return xpert.draft
    }

    async validate(draft: TXpertTeamDraft) {
        const freeNodeValidator = new FreeNodeValidator()

        const results: ChecklistItem[] = []

        const res = await freeNodeValidator.validate(draft)
        results.push(...res)

        // More validators events
        const validators = await this.eventEmitter.emitAsync(EventNameXpertValidate, new XpertDraftValidateEvent(draft))
        validators.forEach((items) => {
            if (items) {
                results.push(...items)
            }
        })
        return results
    }

    async publish(id: string, newVersion: boolean, environmentId: string, notes: string) {
        return await this.commandBus.execute(new XpertPublishCommand(id, newVersion, environmentId, notes))
    }

    async allVersions(id: string) {
        const xpert = await this.findOne(id)
        const { items: allVersions } = await this.findAll({
            where: {
                workspaceId: xpert.workspaceId ?? IsNull(),
                type: xpert.type,
                slug: xpert.slug
            }
        })

        return allVersions.map((item) => ({
            id: item.id,
            version: item.version,
            latest: item.latest,
            publishAt: item.publishAt,
            releaseNotes: item.releaseNotes
        }))
    }

    async setAsLatest(id: string) {
        const xpert = await this.findOne(id)
        if (!xpert.latest) {
            const { items: xperts } = await this.findAll({
                where: {
                    workspaceId: xpert.workspaceId ?? IsNull(),
                    type: xpert.type,
                    slug: xpert.slug,
                    latest: true
                }
            })

            xperts.forEach((item) => (item.latest = false))
            xpert.latest = true
            await this.repository.save([...xperts, xpert])
        }
    }

    async deleteXpert(id: string) {
        const xpert = await this.findOne(id)

        if (xpert.latest) {
            // Delete all versions if it is latest version
            return await this.softDelete({ name: xpert.name, deletedAt: IsNull() })
        } else {
            // Delete current version team
            return await this.softDelete(xpert.id)
        }
    }

    async getUserGroups(id: string, organizationId?: string) {
        const resolvedOrganizationId = await this.userGroupService.resolveAccessibleOrganizationId(organizationId)
        const xpert = await this.findOne(id, {
            relations: ['userGroups']
        })

        return (xpert.userGroups ?? []).filter((group) => group.organizationId === resolvedOrganizationId)
    }

    async updateUserGroups(id: string, ids: string[], organizationId?: string) {
        const resolvedOrganizationId = await this.userGroupService.resolveAccessibleOrganizationId(organizationId)
        const xpert = await this.findOne(id, {
            relations: ['userGroups']
        })

        const uniqueIds = [...new Set((ids ?? []).filter(Boolean))]
        const groups =
            uniqueIds.length > 0
                ? await this.userGroupService.findByIdsInOrganization(resolvedOrganizationId, uniqueIds)
                : []

        if (groups.length !== uniqueIds.length) {
            throw new NotFoundException('Some user groups were not found in the current organization.')
        }

        const preservedGroups = (xpert.userGroups ?? []).filter((group) => group.organizationId !== resolvedOrganizationId)
        xpert.userGroups = [...preservedGroups, ...groups]
        await this.repository.save(xpert)
        return this.getUserGroups(id, resolvedOrganizationId)
    }

    async findBySlug(slug: string, relations?: string[]) {
        return await this.repository.findOne({
            where: {
                slug,
                latest: true,
                publishAt: Not(IsNull())
            },
            relations: uniq((relations ?? []).concat(['user', 'createdBy', 'organization']))
        })
    }

    async createMemory(xpertId: string, body: { type: LongTermMemoryTypeEnum; value: TMemoryQA | TMemoryUserProfile }) {
        const xpert = await this.findOne(xpertId, { relations: ['agent'] })
        const memory = xpert.memory
        const tenantId = RequestContext.currentTenantId()
        const organizationId = RequestContext.getOrganizationId()
        const execution: IXpertAgentExecution = {}
        const embeddings = await this.queryBus.execute(
            new GetXpertMemoryEmbeddingsQuery(tenantId, organizationId, memory, {
                tokenCallback: (token) => {
                    execution.embedTokens += token ?? 0
                }
            })
        )

        await this.commandBus.execute(
            new CopilotStoreBulkPutCommand(
                body.type,
                [body.value],
                [xpertId, body.type || LongTermMemoryTypeEnum.QA],
                embeddings
            )
        )
    }

    async createBulkMemories(
        xpertId: string,
        body: { type: LongTermMemoryTypeEnum; memories: Array<TMemoryQA | TMemoryUserProfile> }
    ) {
        const xpert = await this.findOne(xpertId, { relations: ['agent'] })
        const memory = xpert.memory
        const tenantId = RequestContext.currentTenantId()
        const organizationId = RequestContext.getOrganizationId()
        const execution: IXpertAgentExecution = {}
        const embeddings = await this.queryBus.execute(
            new GetXpertMemoryEmbeddingsQuery(tenantId, organizationId, memory, {
                tokenCallback: (token) => {
                    execution.embedTokens += token ?? 0
                }
            })
        )
        await this.commandBus.execute(
            new CopilotStoreBulkPutCommand(
                body.type,
                body.memories,
                [xpertId, body.type || LongTermMemoryTypeEnum.QA],
                embeddings
            )
        )
    }

    async findAllMemory(id: string, types: string[]) {
        const where = {} as FindOptionsWhere<ICopilotStore>
        const _types = types
        if (_types?.length > 1) {
            where.prefix = In(_types.map((type) => `${id}${type ? `:${type}` : ''}`))
        } else if (_types?.length === 1) {
            const type = _types[0]
            where.prefix = `${id}${type ? `:${type}` : ''}`
        } else {
            where.prefix = Like(`${id}%`)
        }

        try {
            return await this.storeService.findAll({
                where,
                relations: ['createdBy'],
                order: { createdAt: OrderTypeEnum.DESC }
            })
        } catch (err) {
            throw new HttpException(getErrorMessage(err), HttpStatus.INTERNAL_SERVER_ERROR)
        }
    }

    async getMemoryFiles(id: string, path?: string, deepth?: number): Promise<TFileDirectory[]> {
        const xpert = await this.findOne(id)
        return this.createWorkspaceVolumeClient(xpert.tenantId, RequestContext.currentUserId(), xpert.id).list(
            XPERT_MEMORY_WORKSPACE_PATH,
            {
                path,
                deepth
            }
        )
    }

    async getMemoryFile(id: string, filePath: string): Promise<TFile> {
        const xpert = await this.findOne(id)
        return this.createWorkspaceVolumeClient(xpert.tenantId, RequestContext.currentUserId(), xpert.id).readFile(
            XPERT_MEMORY_WORKSPACE_PATH,
            filePath
        )
    }

    async saveMemoryFile(id: string, filePath: string, content: string): Promise<TFile> {
        const xpert = await this.findOne(id)
        return this.createWorkspaceVolumeClient(xpert.tenantId, RequestContext.currentUserId(), xpert.id).saveFile(
            XPERT_MEMORY_WORKSPACE_PATH,
            filePath,
            content
        )
    }

    async uploadMemoryFile(
        id: string,
        folderPath: string,
        file: { originalname: string; buffer: Buffer; mimetype?: string }
    ): Promise<TFile> {
        const xpert = await this.findOne(id)
        return this.createWorkspaceVolumeClient(xpert.tenantId, RequestContext.currentUserId(), xpert.id).uploadFile(
            XPERT_MEMORY_WORKSPACE_PATH,
            folderPath,
            file
        )
    }

    async deleteMemoryFile(id: string, filePath: string): Promise<void> {
        const xpert = await this.findOne(id)
        await this.createWorkspaceVolumeClient(xpert.tenantId, RequestContext.currentUserId(), xpert.id).deleteFile(
            XPERT_MEMORY_WORKSPACE_PATH,
            filePath
        )
    }

    async getTriggerProviders() {
        return this.triggerRegistry.list().map((provider) => ({
            ...provider.meta
        }))
    }

    async getSandboxProviders() {
        return this.sandboxService.listProviders()
    }

    private createWorkspaceVolumeClient(tenantId: string, userId: string, xpertId: string) {
        return new VolumeSubtreeClient(this.createVolumeHandle(tenantId, userId, xpertId), {
            allowRootWorkspace: true
        })
    }

    private createVolumeHandle(tenantId: string, userId: string, xpertId: string) {
        return this.volumeClient.resolve({
            tenantId,
            catalog: 'xperts',
            userId,
            xpertId,
            isolateByUser: true
        })
    }
}
