export enum AiFeatureEnum {
  FEATURE_COPILOT = 'FEATURE_COPILOT',
  FEATURE_COPILOT_KNOWLEDGEBASE = 'FEATURE_COPILOT_KNOWLEDGEBASE',
  FEATURE_COPILOT_CHAT = 'FEATURE_COPILOT_CHAT',
  FEATURE_XPERT = 'FEATURE_XPERT',
}
