export enum AiFeatureEnum {
  FEATURE_COPILOT = 'FEATURE_COPILOT',
  FEATURE_COPILOT_KNOWLEDGEBASE = 'FEATURE_COPILOT_KNOWLEDGEBASE',
  FEATURE_COPILOT_CHAT = 'FEATURE_COPILOT_CHAT',
  FEATURE_XPERT = 'FEATURE_XPERT',
  FEATURE_XPERT_CHATBI = 'FEATURE_XPERT_CHATBI',
  FEATURE_XPERT_CLAWXPERT = 'FEATURE_XPERT_CLAWXPERT',
  FEATURE_XPERT_CODEXPERT = 'FEATURE_XPERT_CODEXPERT',
  FEATURE_XPERT_DEEP_RESEARCH = 'FEATURE_XPERT_DEEP_RESEARCH'
}
