export enum AIPermissionsEnum {
  /**
   * Create or edit Knowledgebase in organization.
   */
  KNOWLEDGEBASE_EDIT = 'KNOWLEDGEBASE_EDIT',
  COPILOT_VIEW = 'COPILOT_VIEW',
  COPILOT_EDIT = 'COPILOT_EDIT',
  MEMBERSHIP_EDIT = 'MEMBERSHIP_EDIT',
  MEMBERSHIP_PURCHASE = 'MEMBERSHIP_PURCHASE',
  MODEL_ACCESS_REQUEST_VIEW = 'MODEL_ACCESS_REQUEST_VIEW',
  MODEL_ACCESS_REQUEST_EDIT = 'MODEL_ACCESS_REQUEST_EDIT',
  MODEL_GATEWAY_USE = 'MODEL_GATEWAY_USE',
  MODEL_GATEWAY_MANAGE = 'MODEL_GATEWAY_MANAGE',
  BILLING_PRODUCT_EDIT = 'BILLING_PRODUCT_EDIT',
  BILLING_REFUND = 'BILLING_REFUND',
  PAYMENT_PROVIDER_EDIT = 'PAYMENT_PROVIDER_EDIT',
  /**
   * Create or edit Xperts in organization.
   */
  XPERT_EDIT = 'XPERT_EDIT',
  CHAT_VIEW = 'CHAT_VIEW'
}
