export enum AIPermissionsEnum {
  /**
   * Create or edit Knowledgebase in organization.
   */
  KNOWLEDGEBASE_EDIT = 'KNOWLEDGEBASE_EDIT',
  COPILOT_VIEW = 'COPILOT_VIEW',
  COPILOT_EDIT = 'COPILOT_EDIT',
  MODEL_USAGE_MONITOR = 'MODEL_USAGE_MONITOR',
  MEMBERSHIP_EDIT = 'MEMBERSHIP_EDIT',
  MEMBERSHIP_USE = 'MEMBERSHIP_USE',
  MODEL_ACCESS_REQUEST_VIEW = 'MODEL_ACCESS_REQUEST_VIEW',
  MODEL_ACCESS_REQUEST_EDIT = 'MODEL_ACCESS_REQUEST_EDIT',
  MODEL_GATEWAY_USE = 'MODEL_GATEWAY_USE',
  MODEL_GATEWAY_MANAGE = 'MODEL_GATEWAY_MANAGE',
  BILLING_PRODUCT_EDIT = 'BILLING_PRODUCT_EDIT',
  BILLING_REFUND = 'BILLING_REFUND',
  PAYMENT_PROVIDER_EDIT = 'PAYMENT_PROVIDER_EDIT',
  /**
   * Create or edit Xperts in organization.
   */
  XPERT_EDIT = 'XPERT_EDIT',
  XPERT_PROJECT_VIEW = 'XPERT_PROJECT_VIEW',
  XPERT_PROJECT_CREATE = 'XPERT_PROJECT_CREATE',
  XPERT_PROJECT_EDIT = 'XPERT_PROJECT_EDIT',
  XPERT_PROJECT_MANAGE = 'XPERT_PROJECT_MANAGE',
  CHAT_VIEW = 'CHAT_VIEW',
  EVOLUTION_VIEW = 'EVOLUTION_VIEW',
  EVOLUTION_MANAGE = 'EVOLUTION_MANAGE'
}
