import {
  Activity,
  Apple,
  ArrowDown,
  ArrowDownToLine,
  ArrowDownAz,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpToLine,
  ArrowUpRight,
  ArrowUpDown,
  Award,
  BadgeCheck,
  BadgePlus,
  Ban,
  Bell,
  Bookmark,
  Bot,
  Brain,
  BookOpenText,
  Blocks,
  Braces,
  BringToFront,
  BriefcaseBusiness,
  Building2,
  Calendar,
  ChartColumnIncreasing,
  ChartPie,
  ChartSpline,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CircleDot,
  CircleMinus,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleUserRound,
  CircleX,
  ClipboardPaste,
  Copy,
  CodeXml,
  Database,
  DollarSign,
  Download,
  Ellipsis,
  EllipsisVertical,
  Expand,
  ExternalLink,
  Factory,
  Filter,
  FileArchive,
  FilePenLine,
  FlipHorizontal,
  Focus,
  FoldVertical,
  FolderPlus,
  FolderTree,
  FolderX,
  Folders,
  Globe,
  GraduationCap,
  Group,
  GripVertical,
  Hand,
  HardHat,
  HardDrive,
  Heart,
  House,
  LayoutDashboard,
  ListIndentIncrease,
  ListMinus,
  ListPlus,
  ListX,
  Languages,
  Layers,
  Link2,
  LoaderPinwheel,
  Lock,
  MapPinned,
  Mail,
  MemoryStick,
  Menu,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquarePlus,
  Minimize,
  MonitorSmartphone,
  Network,
  NotebookPen,
  NotebookTabs,
  Palette,
  PaintBucket,
  PanelLeftOpen,
  PanelsTopLeft,
  Percent,
  Paperclip,
  Pipette,
  Pin,
  Plus,
  Puzzle,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Rows3,
  Ruler,
  SaveAll,
  ScanText,
  SendToBack,
  ShieldCheck,
  ShieldUser,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Smartphone,
  SquarePen,
  Star,
  Table2,
  Tablet,
  Tag,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  TextSelect,
  TriangleAlert,
  ToggleRight,
  Trash2,
  TrendingUp,
  Truck,
  UnfoldVertical,
  Undo2,
  Upload,
  UserPlus,
  UserRoundCog,
  Users,
  UsersRound,
  WandSparkles,
  Waypoints,
  Wheat,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIconData,
} from 'lucide-angular';

import type { ZardIconAssetMap } from './icon-assets';

export type ResolvedZardIcon =
  | { kind: 'lucide'; icon: LucideIconData }
  | { kind: 'asset'; src: string }
  | { kind: 'class'; className: string }
  | null;

const LEGACY_LUCIDE_ICONS: Record<string, LucideIconData> = {
  account_circle: CircleUserRound,
  account_tree: FolderTree,
  add: Plus,
  add_circle_outline: CirclePlus,
  add_comment: MessageSquarePlus,
  add_link: Waypoints,
  addchart: ChartColumnIncreasing,
  adjust: CircleDot,
  agriculture: Wheat,
  analytics: ChartSpline,
  apple: Apple,
  alternate_email: UserRoundCog,
  approval: BadgeCheck,
  arrow_back: ArrowLeft,
  arrow_drop_down: ChevronDown,
  arrow_drop_up: ChevronUp,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_forward_ios: ChevronRight,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  arrow_upward: ArrowUp,
  assistant_direction: Waypoints,
  attach_file: Paperclip,
  auto_awesome: Sparkles,
  auto_fix_high: WandSparkles,
  auto_stories: BookOpenText,
  autorenew: RefreshCw,
  block: Ban,
  bookmark: Bookmark,
  bookmark_add: BadgePlus,
  browse_activity: Activity,
  business_center: BriefcaseBusiness,
  cancel: CircleX,
  category: Blocks,
  center_focus_strong: Focus,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  check_small: CircleCheckBig,
  clear: X,
  clear_all: ListX,
  close: X,
  color_lens: Palette,
  collections: Folders,
  comment: MessageSquare,
  construction: Wrench,
  content_copy: Copy,
  content_paste: ClipboardPaste,
  corporate_fare: Building2,
  create_new_folder: FolderPlus,
  css: CodeXml,
  data_array: Braces,
  data_table: Table2,
  data_usage: ChartSpline,
  database: Database,
  dashboard: LayoutDashboard,
  dataset_linked: Link2,
  delete: Trash2,
  delete_forever: Trash2,
  delete_outline: Trash2,
  deployed_code: CodeXml,
  devices: MonitorSmartphone,
  drag_handle: GripVertical,
  drag_indicator: GripVertical,
  document_scanner: ScanText,
  done: CircleCheckBig,
  drive_file_move: Waypoints,
  drive_file_rename_outline: FilePenLine,
  dvr: LayoutDashboard,
  edit: SquarePen,
  edit_attributes: SquarePen,
  edit_off: SquarePen,
  engineering: HardHat,
  error_outline: CircleAlert,
  email: Mail,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  explore: Focus,
  extension: Puzzle,
  face: CircleUserRound,
  feedback: MessageCircleQuestion,
  file_download: Download,
  file_upload: Upload,
  filter: Filter,
  filter_alt: Filter,
  filter_center_focus: Focus,
  first_page: ChevronLeft,
  flip: FlipHorizontal,
  flip_to_back: SendToBack,
  flip_to_front: BringToFront,
  folder_delete: FolderX,
  folder_zip: FileArchive,
  format_align_center: TextAlignCenter,
  format_align_justify: TextAlignJustify,
  format_align_left: TextAlignStart,
  format_align_right: TextAlignEnd,
  format_color_fill: PaintBucket,
  format_indent_increase: ListIndentIncrease,
  format_list_numbered: Rows3,
  fullscreen: Expand,
  fullscreen_exit: Minimize,
  functions: Braces,
  generating_tokens: Sparkles,
  group: UsersRound,
  group_add: UsersRound,
  group_work: Group,
  hub: Network,
  help_outline: MessageCircleQuestion,
  history_edu: NotebookPen,
  home: House,
  interests: Heart,
  invert_colors: Pipette,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_left: ChevronLeft,
  keyboard_arrow_right: ChevronRight,
  keyboard_arrow_up: ChevronUp,
  label: Tag,
  last_page: ChevronRight,
  launch: ExternalLink,
  layers_clear: Layers,
  leaderboard: ChartColumnIncreasing,
  lightbulb: Sparkles,
  link: Link2,
  lock: Lock,
  low_priority: ArrowDownRight,
  local_shipping: Truck,
  local_grocery_store: ShoppingCart,
  manage_accounts: UserRoundCog,
  manufacturing: Factory,
  map: MapPinned,
  memory: MemoryStick,
  menu: Menu,
  menu_open: PanelLeftOpen,
  monetization_on: DollarSign,
  military_tech: Award,
  more_horiz: Ellipsis,
  more_vert: EllipsisVertical,
  navigate_before: ChevronLeft,
  navigate_next: ChevronRight,
  new_label: BadgePlus,
  north: ArrowUp,
  north_east: ArrowUpRight,
  notifications: Bell,
  open_in_new: ExternalLink,
  pan_tool: Hand,
  pending: LoaderPinwheel,
  people: Users,
  people_outline: UsersRound,
  percent: Percent,
  person_add: UserPlus,
  pie_chart: ChartPie,
  pivot_table_chart: Table2,
  play_circle: CirclePlay,
  playlist_add: ListPlus,
  playlist_remove: ListMinus,
  public: Globe,
  psychology: Brain,
  push_pin: Pin,
  query_stats: ChartColumnIncreasing,
  quiz: MessageCircleQuestion,
  redo: RefreshCcw,
  refresh: RefreshCw,
  remove: CircleMinus,
  remove_circle_outline: CircleMinus,
  restart_alt: RotateCcw,
  robot_2: Bot,
  room_preferences: House,
  save_as: SaveAll,
  school: GraduationCap,
  sell: Tag,
  share: Link2,
  segment: Rows3,
  settings_applications: LayoutDashboard,
  settings_suggest: SlidersHorizontal,
  south: ArrowDown,
  south_east: ArrowDownRight,
  sort: ArrowUpDown,
  sort_by_alpha: ArrowDownAz,
  stars: Star,
  stay_primary_landscape: Tablet,
  stay_primary_portrait: Smartphone,
  stop_circle: CircleStop,
  storage: HardDrive,
  style: PaintBucket,
  straighten: Ruler,
  subscriptions: NotebookTabs,
  supervisor_account: ShieldUser,
  swap_horiz: ArrowUpDown,
  system_update_alt: Download,
  table_view: Table2,
  task_alt: CircleCheckBig,
  text_format: TextSelect,
  text_rotation_angleup: TextSelect,
  texture: PanelsTopLeft,
  timeline: ChartSpline,
  toggle_on: ToggleRight,
  tips_and_updates: Sparkles,
  today: Calendar,
  translate: Languages,
  trending_flat: ArrowRight,
  trending_up: TrendingUp,
  try: Sparkles,
  tune: SlidersHorizontal,
  undo: Undo2,
  unfold_less: FoldVertical,
  unfold_more: UnfoldVertical,
  update: RefreshCw,
  upload: Upload,
  verified_user: ShieldCheck,
  vertical_align_bottom: ArrowDownToLine,
  vertical_align_top: ArrowUpToLine,
  warning: TriangleAlert,
  warning_amber: TriangleAlert,
  widgets: Blocks,
  workspaces: PanelsTopLeft,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
};

function isDirectAsset(value: string | null | undefined): boolean {
  return !!value && (value.startsWith('data:') || value.startsWith('/') || value.startsWith('./') || value.startsWith('../'));
}

function isClassIcon(value: string | null | undefined): boolean {
  if (!value) {
    return false;
  }

  return value.startsWith('ri-') || value.startsWith('fa-') || value.includes(' fa-') || value.includes(' ri-') || value.includes(' ');
}

export function resolveLegacyIcon(
  icon: string | null | undefined,
  options: {
    svgIcon?: string | null;
    assets?: ZardIconAssetMap;
  } = {},
): ResolvedZardIcon {
  const assets = options.assets ?? {};
  const svgIcon = options.svgIcon?.trim();

  if (svgIcon) {
    return assets[svgIcon]
      ? { kind: 'asset', src: assets[svgIcon] }
      : isDirectAsset(svgIcon)
        ? { kind: 'asset', src: svgIcon }
        : null;
  }

  const normalizedIcon = icon?.trim();
  if (!normalizedIcon) {
    return null;
  }

  if (assets[normalizedIcon]) {
    return { kind: 'asset', src: assets[normalizedIcon] };
  }

  if (isDirectAsset(normalizedIcon)) {
    return { kind: 'asset', src: normalizedIcon };
  }

  const lucideIcon = LEGACY_LUCIDE_ICONS[normalizedIcon];
  if (lucideIcon) {
    return { kind: 'lucide', icon: lucideIcon };
  }

  if (isClassIcon(normalizedIcon)) {
    return { kind: 'class', className: normalizedIcon };
  }

  return null;
}
