const vars = {
  // https://daisyui.com/docs/colors/
  'base-content': 'var(--color-base-content)',
  'surface-container': 'var(--ngm-color-surface-container)',

  // Custom colors
  'text-primary': 'var(--color-text-primary)',
  'text-secondary': 'var(--color-text-secondary)',
  'text-tertiary': 'var(--color-text-tertiary)',
  'text-quaternary': 'var(--color-text-quaternary)',
  'text-destructive': 'var(--color-text-destructive)',
  'text-success': 'var(--color-text-success)',
  'text-warning': 'var(--color-text-warning)',
  'text-destructive-secondary': 'var(--color-text-destructive-secondary)',
  'text-success-secondary': 'var(--color-text-success-secondary)',
  'text-warning-secondary': 'var(--color-text-warning-secondary)',
  'text-accent': 'var(--color-text-accent)',
  'text-primary-on-surface': 'var(--color-text-primary-on-surface)',
  'text-placeholder': 'var(--color-text-placeholder)',
  'text-disabled': 'var(--color-text-disabled)',
  'text-accent-secondary': 'var(--color-text-accent-secondary)',
  'text-accent-light-mode-only': 'var(--color-text-accent-light-mode-only)',
  'text-text-selected': 'var(--color-text-text-selected)',
  'text-secondary-on-surface': 'var(--color-text-secondary-on-surface)',
  'text-logo-text': 'var(--color-text-logo-text)',
  'text-empty-state-icon': 'var(--color-text-empty-state-icon)',
  'text-inverted': 'var(--color-text-inverted)',

  'divider-subtle': 'var(--color-divider-subtle)',
  'divider-regular': 'var(--color-divider-regular)',
  'divider-deep': 'var(--color-divider-deep)',
  'divider-burn': 'var(--color-divider-burn)',
  'divider-intense': 'var(--color-divider-intense)',
  'divider-solid': 'var(--color-divider-solid)',
  'divider-solid-alt': 'var(--color-divider-solid-alt)',

  'hover-bg': 'var(--color-hover-bg)',
  'danger-bg': 'var(--color-danger-bg)',
  'state-base-hover': 'var(--color-hover-bg)',
  'state-destructive-hover': 'var(--color-state-destructive-hover)',
  'background-default-hover': 'var(--color-hover-bg)',

  'token-main-surface-primary': 'var(--main-surface-primary)',
  'token-main-surface-secondary': 'var(--main-surface-secondary)',
  'token-main-surface-low': 'var(--ngm-color-surface-container-low)',
  'token-text-secondary': 'var(--text-secondary)',
  'token-border-medium': 'var(--border-medium)',
  'token-border-light': 'var(--border-light)',
  'components-card-option-selected-border': 'var(--components-card-option-selected-border)',
  'components-card-bg': 'var(--color-components-card-bg)',
  'components-panel-bg': 'var(--color-components-panel-bg)',
  'components-panel-bg-blur': 'var(--color-components-panel-bg-blur)',
  'components-panel-border': 'var(--color-components-panel-border)',
  'components-button-primary-text': 'var(--color-components-button-primary-text)',
  'components-button-primary-border': 'var(--color-components-button-primary-border)',
  'components-button-primary-bg': 'var(--color-components-button-primary-bg)',
  'components-button-secondary-bg': 'var(--color-components-button-secondary-bg)',
  'components-button-secondary-bg-hover': 'var(--color-components-button-secondary-bg-hover)',
  'components-dropzone-bg': 'var(--color-components-dropzone-bg)',
  'components-input-bg': 'var(--color-components-input-bg)',
  'components-input-bg-normal': 'var(--color-components-input-bg-normal)',
  'components-input-bg-hover': 'var(--color-components-input-bg-hover)',
  'components-input-bg-active': 'var(--color-components-input-bg-active)',
  'components-input-border-hover': 'var(--color-components-input-border-hover)',
  'components-input-border-active': 'var(--color-components-input-border-active)',
  'components-input-text-placeholder': 'var(--color-components-input-text-placeholder)',
  'components-list-option-bg': 'var(--color-components-list-option-bg)',
  'components-list-option-active-bg': 'var(--color-components-list-option-active-bg)',
  'components-toggle-bg': 'var(--color-components-toggle-bg)',
  'components-toggle-bg-unchecked': 'var(--color-components-toggle-bg-unchecked)',
  'components-toggle-knob': 'var(--color-components-toggle-knob)',
  'components-kbd-bg-white': 'var(--color-components-kbd-bg-white)',
  'components-checkbox-bg': 'var(--color-components-checkbox-bg)',
  'components-option-card-option-selected-border': 'var(--color-components-option-card-option-selected-border)',
  'button-ghost-hover': 'var(--color-hover-bg)',
  'surface-container-bg': 'var(--ngm-color-surface-container)'
}

export default vars
